language: cpp
dist: trusty

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.9
      - g++-4.9
      - valgrind

matrix:
  include:
    - os: linux # GCC 5
      compiler: gcc
      env: MATRIX_EVAL="CXX=g++-5"
    - os: linux # GCC 4.8
      compiler: gcc
    - os: linux
      compiler: clang

script:
  - $CXX -v
  - $CXX -std=c++11 -Wall -I. tests/main.cpp tests/test-pimpl.cpp tests/test-incomplete.cpp -o main.t && ./main.t
  - valgrind --leak-check=yes --error-exitcode=1 ./main.t
  
