language: cpp
dist: trusty

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - boost-latest
    packages:
      - gcc-4.9
      - g++-4.9
      - libboost1.55-all-dev
      - valgrind

matrix:
  include:
    - os: linux # GCC 5
      compiler: gcc
      env: MATRIX_EVAL="CXX=g++-5"
    - os: linux # GCC 4.8
      compiler: gcc
    - os: linux
      compiler: clang

script:
  - $CXX -v
  - $CXX -std=c++11 -Wall -DBOOST_TEST_DYN_LINK -I. -c tests/main.cpp -o main.o
  - $CXX main.o -o main.t -lboost_unit_test_framework -lpthread
  - valgrind --leak-check=yes --error-exitcode=1 ./main.t
  
